"""Changes done

Revision ID: 3c640f84f86b
Revises: 001_initial_schema
Create Date: 2025-11-29 20:06:49.081578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c640f84f86b'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_vouchers', 'status',
               existing_type=postgresql.ENUM('pending', 'paid', 'partial', name='paymentstatus'),
               type_=sa.Enum('pending', 'paid', 'partial', name='paymentstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::paymentstatus"))
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('open', 'active', 'hold', 'closed', name='projectstatus'),
               type_=sa.Enum('open', 'active', 'hold', 'closed', name='projectstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'open'::projectstatus"))
    op.alter_column('timesheets', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='timesheetstatus'),
               type_=sa.Enum('pending', 'approved', 'rejected', name='timesheetstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::timesheetstatus"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'project_lead', 'project_owner', 'developer', name='userrole'),
               type_=sa.Enum('super_admin', 'project_lead', 'project_owner', 'developer', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'project_lead', 'project_owner', 'developer', name='userrole', native_enum=False),
               type_=postgresql.ENUM('super_admin', 'project_lead', 'project_owner', 'developer', name='userrole'),
               existing_nullable=False)
    op.alter_column('timesheets', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='timesheetstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='timesheetstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::timesheetstatus"))
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('open', 'active', 'hold', 'closed', name='projectstatus', native_enum=False),
               type_=postgresql.ENUM('open', 'active', 'hold', 'closed', name='projectstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'open'::projectstatus"))
    op.alter_column('payment_vouchers', 'status',
               existing_type=sa.Enum('pending', 'paid', 'partial', name='paymentstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'paid', 'partial', name='paymentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::paymentstatus"))
    # ### end Alembic commands ###

